apiVersion: v1
kind: Service
metadata:
  name: front-back-service
spec:
  selector:
    app: front-back  # Garante que o serviço está associado ao Deployment correto
  ports:
    - name: http
      port: 80          # Porta externa (para o frontend)
      targetPort: 80   # Porta interna no contêiner para o frontend
      nodePort: 30080    # Porta externa no nó para o frontend
    - name: backend
      port: 3000        # Porta externa (para o backend)
      targetPort: 3000   # Porta interna no contêiner para o backend
      nodePort: 30300    # Porta externa no nó para o backend
  type: NodePort       # Tipo NodePort
