apiVersion: v1
kind: Service
metadata:
  name: front-back-service
spec:
  selector:
    app: front-back  # Certifique-se de que o 'app' no Deployment é 'front-back'
  ports:
    - name: http
      protocol: TCP
      port: 80          # Porta que será exposta externamente para o frontend
      targetPort: 3080   # A porta do pod que será mapeada para a porta externa
    - name: backend
      protocol: TCP
      port: 3000        # Porta que será exposta externamente para o backend
      targetPort: 3000   # A porta no pod que será mapeada para a porta externa
  type: LoadBalancer  # Tipo de serviço, pode ser LoadBalancer, NodePort ou ClusterIP
