apiVersion: v1
kind: Service
metadata:
  name: front-back-service
spec:
  selector:
    app: front-back  # O mesmo valor do selector no Deployment
  ports:
    - protocol: TCP
      port: 80          # Porta que será exposta externamente
      targetPort: 80     # A porta no pod que será mapeada para a porta externa
    - protocol: TCP
      port: 3000        # Porta que será exposta externamente para o backend
      targetPort: 3000   # A porta no pod que será mapeada para a porta externa
  type: LoadBalancer   # Tipo de serviço. Pode ser LoadBalancer, NodePort ou ClusterIP.
