apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: front-back
spec:
  serviceName: "front-back"  # Nome do serviço associando ao StatefulSet
  replicas: 2  # Número de pods desejados
  selector:
    matchLabels:
      app: front-back
  template:
    metadata:
      labels:
        app: front-back
    spec:
      containers:
      - name: front-back
        image: felpsxill/malware-app:frontend-backend-latest  # Nome correto da imagem
        imagePullPolicy: Always
        ports:
        - containerPort: 3000  # Backend na porta 3000
        - containerPort: 3080  # Frontend na porta 80
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mysql-secrets  # Usando o segredo correto
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secrets  # Usando o segredo correto
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets  # Usando o segredo correto
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-secrets  # Usando o segredo correto
                key: DB_NAME
      volumeClaimTemplates:  # Persistência de dados para o StatefulSet
        - metadata:
            name: front-back-pvc  # Nome do PVC (Persistent Volume Claim)
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi  # Tamanho do volume, ajustável conforme necessário
  restartPolicy: Always
